name: Deploy Backend (Fly.io)

on:
  push:
    branches: [main]
    paths:
      - 'scireda-api/**'
      - 'fly.toml'
      - '.github/workflows/deploy-back.yml'
  workflow_dispatch: {}  # déclenchement manuel possible

concurrency:
  group: deploy-back-${{ github.ref }}
  cancel-in-progress: false

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build_and_deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.expose-url.outputs.url || '' }}
    defaults:
      run:
        working-directory: scireda-api

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Fly Deploy
        run: flyctl deploy --remote-only --build-arg NODE_ENV=production

      - name: Health check
        run: curl -f https://scireda-api.fly.dev/health

      - name: Expose URL
        id: expose-url
        run: echo "url=https://scireda-api.fly.dev" >> $GITHUB_OUTPUT